version: '3'

services:
  db:
    container_name: blog
    image: mysql:8.0.30
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DB: ${DB_DATABASE}
